packages:
  - 'apps/*'
  - 'packages/*'
overrides:
  react-dom: 19.2.3
allowBuilds:
  es5-ext: true
  esbuild: true
  nx: true
  unrs-resolver: false
minimumReleaseAgeExclude:
  - '@expo/cli@57.0.13'
  - '@expo/config-plugins@57.0.7'
  - babel-preset-expo@57.0.6
  - expo-asset@57.0.9
  - expo-file-system@57.0.2
  - expo-image-manipulator@57.0.8
  - expo-image-picker@57.0.8
  - expo-modules-core@57.0.10
  - expo@57.0.11
  - tsx@4.23.9
